name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: abandoned
        uses: RelationalAI/abandoned@main
        with:
          days: 7
          repository: RelationalAI/rai-cli
          token: ${{ github.token }}
      - run: |
          length=$(jq '. | length' <<< ${{toJson(steps.abandoned.outputs.pulls) }})
          echo Found $length abandoned PRs
