name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: abandoned
        uses: RelationalAI/abandoned@main
        with:
          days: 7
          repository: facebook/react
          token: ${{ github.token }}
      - run: "echo PRs: ${{ steps.abandoned.outputs.pulls }}"